name: Auto Code Format

on:
    pull_request:
        branches:
            - main

permissions:
    contents: write

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Prettify code
              uses: creyD/prettier_action@v4.6
              with:
                  prettier_options: '--write **/*.{ts,js,json,html}'
                  only_changed: true
